name: ispgaya_ant
description: "An application for controlling a small robot ant through bluetooth."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^12.0.0+1
  
  animated_splash_screen: ^1.3.0
  page_transition: ^2.2.1
  shared_preferences: ^2.5.3

  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.1.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/appIcon.png"
  adaptive_icon_foreground: "assets/icon/foreground.png"
  adaptive_icon_background: "assets/icon/background.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
